version: '3.8'

services:
  mySqlDb:
    image: mysql:8.0
    env_file:
      - ./.env
    container_name: db_lava_autos
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_DOCKER_PORT}:${MYSQL_DOCKER_PORT}"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - lava-autos-network

  app:
    build: .
    depends_on:
      mySqlDb:
        condition: service_healthy
    environment:
       - MYSQL_HOST=mySqlDb
    ports:
      - "4000:4000"
    networks:
      - lava-autos-network

networks:
  lava-autos-network:
    driver: bridge

