version: '3.8'

services:
  mySqlDb:
    image: mysql:8.0
    env_file:
      - ./.env
    container_name: db_lava_autos
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_DOCKER_PORT}:${MYSQL_DOCKER_PORT}"

  app:
    build: .
    depends_on:
      - mySqlDb
    links:
      - mySqlDb
    ports:
      - "4000:4000"

