POST http://localhost:4000/api/login
Content-Type: application/json

{
    "email": "carlos_97.eog97@gmail.com",
    "password": "caeforga"
}

###
GET http://localhost:4000/api/login

###
GET http://localhost:4000/api/users

###
POST http://localhost:4000/api/users
Content-Type: application/json

{
    "email": "carlos_979.eog97@gmail.com",
    "password": "caeforga",
    "username": "carlosO"
}

###
DELETE http://localhost:4000/api/users/2